spring:
  datasource:
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/softProject


server:
  port: 8091


mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml

jwt:
  secret: mySecretKey
  expiration: 3600000  # 1 hour